### PR TITLE
Use the unicode copyright symbol U+00A9

### PR DESCRIPTION
**Pull request by mightyiam**
Since we're using unicode, would there be an issue with that?

### CODE REVIEW

**Comment by mightyiam** [comment]
Closes #3.

**Comment by jonschlinkert** [comment]
> would there be an issue with that?

not at all, unicode is the closest to omni-usable as we'll get. thanks!

**Comment by mightyiam** [comment]
Thank you.

**Comment by tunnckoCore** [comment]
that sucks, lol.
It is international and old school pattern and all of us know what is it.

**Pull request merged**
